= 创建库模块

库模块只是自定义类、函数、扩展函数、扩展属性和全局属性的集合。

NOTE: 顺序很重要。如果 A 依赖于 B，则将 B 放在 A 之前。

== Kotlite 解释器 API

让我们从提供自定义函数开始。通常过程是这样的：

[mermaid]
----
flowchart TD
    Call["函数调用"] --> Unwrap["将 Kotlite 参数值解包为 Kotlin 值"] --> Process["处理（自定义逻辑）"] --> Wrap["将 Kotlin 值包装为 Kotlite 值或提供 Kotlite 常量"] --> Return["返回包装后的值"]
----

在 `CustomFunctionDefinition` 中，`executable` lambda 参数如下所示：

[source, kotlin]
----
{ interpreter: Interpreter, receiver: RuntimeValue?, args: List<RuntimeValue>, typeArgs: Map<String, DataType> ->
    // ...
}
----

NOTE: 对于自定义属性，API 和过程是相似的。本节也适用于它们。

=== RuntimeValue -- 包装 Kotlin 值的 Kotlite 值

在代码级别，Kotlin 主机中的 Kotlite 值是一个 `RuntimeValue`。将 Kotlin 值包装为 `RuntimeValue` 需要技巧。下面列出了如何包装它们。

[cols="20,80a"]
|===
|Kotlin 类型 |转换为 Kotlite 值的代码

|`Int`
|[source, kotlin]
----
IntValue(value: Int, symbolTable: SymbolTable)
----

|`Long`
|[source, kotlin]
----
LongValue(value: Long, symbolTable: SymbolTable)
----

|`Double`
|[source, kotlin]
----
DoubleValue(value: Double, symbolTable: SymbolTable)
----

|`Byte`
|[source, kotlin]
----
ByteValue(value: Byte, symbolTable: SymbolTable)
----

|`Boolean`
|[source, kotlin]
----
BooleanValue(value: Boolean, symbolTable: SymbolTable)
----

|`String`
|[source, kotlin]
----
StringValue(value: String, symbolTable: SymbolTable)
----

|`Null`
|[source, kotlin]
----
NullValue
----

|`Unit`
|[source, kotlin]
----
UnitValue
----

|非泛型对象
|[source, kotlin]
----
DelegatedValue<T>(value: T, clazz: ClassDefinition, symbolTable: SymbolTable)
----

其中 `T` 是 Kotlin 值的类型，`clazz` 是该值的 Kotlite <<_classdefinition_and_providedclassdefinition,类定义>>。

|泛型对象
|[source, kotlin]
----
DelegatedValue<T>(value: T, clazz: ClassDefinition, symbolTable: SymbolTable, typeArguments: List<DataType>)
----

其中 `T` 是 Kotlin 值的类型，`clazz` 是该值的 Kotlite <<_classdefinition_and_providedclassdefinition,类定义>>。

|标准库支持的对象
|非详尽列表：
[source, kotlin]
----
ByteArrayValue(value: ByteArray, symbolTable: SymbolTable)

PairValue(value: Pair<RuntimeValue, RuntimeValue>, typeA: DataType, typeB: DataType, symbolTable: SymbolTable)

ListValue(value: List<RuntimeValue>, typeArgument: DataType, symbolTable: SymbolTable)

MutableMapValue(value: MutableMap<RuntimeValue, RuntimeValue>, keyType: DataType, valueType: DataType, symbolTable: SymbolTable)
----

示例：
[source, kotlin]
----
val symbolTable = interpreter.symbolTable()
val wrappedValue = ListValue(
    value = listOf(1, 2, 3, 5, 10),
    typeArgument = symbolTable.IntType,
    symbolTable = symbolTable,
)
----

|===

CAUTION: 对于像 `List`、`Map` 或 `Pair` 这样的嵌套类，别忘了包装所有嵌套值。否则，事情会出错，并且在代码执行期间可能会抛出异常。

=== SymbolTable

可以通过 `Interpreter.symbolTable()` 获取 `SymbolTable`。`SymbolTable` 不能被持久化，因为它在另一个函数调用的上下文中可能不同，并且持久化它会导致内存泄漏。

=== ClassDefinition 和 ProvidedClassDefinition

对于标准库中可用的类型，通常可以通过 `${TypeName}Class.clazz` 找到。例如，`MutableListClass.clazz` 用于类 `MutableList`。

对于 Kotlite 未知的类型，您将必须提供一个自定义的 `ClassDefinition`。

`ProvidedClassDefinition` 是一个为库用户定义类的友好 API。它扩展了 `ClassDefinition`。可以在 <<ProvidedClassDefinitionExample,这里>> 找到一个示例。

=== DataType

如果需要创建泛型 Kotlite 值，例如，一个 `List<T>` 值，需要一个或多个 `DataType` 来指定类型参数。可以从多种方式获取它。

1. 如果它在函数调用的类型参数中可用，请使用 `typeArgs[name]`。

例如，对于像这样的函数签名：
[source, kotlin]
----
fun <T, R : Comparable<R>> MutableList<T>.sortBy(selector: (T) -> R?)
----

`typeArgs["T"]` 是 `DataType` 中的 `T` 类型参数，`typeArgs["R"]` 是 `DataType` 中的 `R` 类型参数。

[start=2]
2. 基本数据类型

可以从 `SymbolTable` 获取。例如，`symbolTable.IntType`。对于一些特殊类型，如 `Any`、`Unit` 和 `Nothing`，可以直接构造：`UnitType(isNullable: Boolean = false)`。

[start=3]
3. 对于其他类型，可以通过便捷扩展函数 `String.toDataType(symbolTable: SymbolTable)` 获取。例如，

[source, kotlin]
----
val symbolTable: SymbolTable = interpreter.symbolTable()

val byteArrayType: DataType = "ByteArray".toDataType(symbolTable)
val pairType: DataType = "Pair<String, Pair<Double, Int>>".toDataType(symbolTable)
val genericType: DataType = "Map<K, Int>".toDataType(symbolTable)
----

CAUTION: 如果有不受信任的用户输入，此方法容易受到 https://owasp.org/www-community/Injection_Theory[注入攻击]。

=== 将 Kotlite `RuntimeValue` 解包为 Kotlin 值

这相对简单。只需转换为正确的类型并调用成员属性 `.value`。

[cols="20,80a"]
|===
|Kotlin 类型 |将 Kotlite 值转换为 Kotlin 值的代码

|`Int`
|[source, kotlin]
----
val actualValue: Int = (value as IntValue).value
val nullableActualValue: Int? = (value as? IntValue)?.value
----

|`Long`
|[source, kotlin]
----
val actualValue: Long = (value as LongValue).value
val nullableActualValue: Long? = (value as? LongValue)?.value
----

|`Double`
|[source, kotlin]
----
val actualValue: Double = (value as DoubleValue).value
val nullableActualValue: Double? = (value as? DoubleValue)?.value
----

|`Byte`
|[source, kotlin]
----
val actualValue: Byte = (value as ByteValue).value
val nullableActualValue: Byte? = (value as? ByteValue)?.value
----

|`Boolean`
|[source, kotlin]
----
val actualValue: Boolean = (value as BooleanValue).value
val nullableActualValue: Boolean? = (value as? BooleanValue)?.value
----

|`String`
|[source, kotlin]
----
val actualValue: String = (value as StringValue).value
val nullableActualValue: String? = (value as? StringValue)?.value
----

|Object
|[source, kotlin]
----
val byteArray: ByteArray = (value as DelegatedValue<ByteArray>).value
val nullableByteArray: ByteArray? = (value as? DelegatedValue<ByteArray>)?.value

val list: List<RuntimeValue> = (value as DelegatedValue<List<RuntimeValue>>).value
val listWithIntValue: List<Int> = list.map {
    (it as IntValue).value
}
----
|===

CAUTION: 对于像 `List`、`Map` 或 `Pair` 这样的嵌套类，必要时别忘了解包所有嵌套值。

== 手动方法

创建一个扩展抽象类 `LibraryModule` 的类，给它命名，包含所有实现，然后这个类就是一个可以安装的库模块。

采用这种方法具有最佳性能，但需要编写大量重复代码。

标准库中的 `IOLibModule` 是一个值得参考的好示例，因为它是一个完全手工编写的库模块。

.`IOLibModule`
[%collapsible%open]
====
./stdlib/src/commonMain/kotlin/com/sunnychung/lib/multiplatform/kotlite/stdlib/IOLibModule.kt
[source, kotlin]
----
include::../../stdlib/src/commonMain/kotlin/com/sunnychung/lib/multiplatform/kotlite/stdlib/IOLibModule.kt[]
----
====

== 委托方法

这种方法是大多数 Kotlite 标准库采用的方法。将所有内容委托给 Kotlin，并使用 Kotlite 标准库处理器 Gradle 插件生成所有委托代码。

在委托调用执行期间，Kotlite 会在需要时将 Kotlite `RuntimeValue` 解包为 Kotlin 类型，执行委托函数，然后将结果包装为 Kotlite `RuntimeValue`。当主体、参数或结果是具有大尺寸的 `Collection` 时，时间性能损失会很显著。

下面是一个生成委托库模块的最小示例。示例中采用了 `Regex` 和 `Collection` 库模块中的一些内容。

./settings.gradle.kts
[source, kotlin]
----
pluginManagement {
    repositories {
        mavenCentral()
        // ...
    }
}
----

Kotlite 库预处理器 Gradle 插件 image:https://img.shields.io/maven-central/v/io.github.sunny-chung/kotlite-stdlib-processor-plugin[]

./your-library/build.gradle.kts
[source, kotlin]
----
plugins {
    kotlin("multiplatform")
    id("io.github.sunny-chung.kotlite-stdlib-processor-plugin") version "<version>"
}

// ...

kotlin {
    sourceSets {
        val commonMain by getting {
            dependencies {
                // ...
            }
            kotlin.srcDir(tasks.named("kotliteStdlibHeaderProcess").map { it.outputs })
        }

// ...

kotliteStdLibHeaderProcessor {
    inputDir = "src/kotlinheader/"
    outputDir = "build/generated/common/"
    outputPackage = "com.sunnychung.lib.multiplatform.kotlite.stdlib"
    configs = mapOf(
        "Regex" to KotliteModuleConfig(
            imports = listOf(
                "com.sunnychung.lib.multiplatform.kotlite.stdlib.regex.RegexClass",
                "com.sunnychung.lib.multiplatform.kotlite.stdlib.regex.RegexValue",
            )
        ),
    )
}
----

[#ProvidedClassDefinitionExample]
实现委托类和值工厂函数。

./stdlib/src/commonMain/kotlin/com/sunnychung/lib/multiplatform/kotlite/stdlib/regex/RegexValue.kt
[source, kotlin]
----
fun RegexValue(value: Regex, symbolTable: SymbolTable) : DelegatedValue<Regex>
    = DelegatedValue<Regex>(value, "Regex", RegexClass.clazz, symbolTable = symbolTable)

object RegexClass {
     val clazz = ProvidedClassDefinition(
         fullQualifiedName = "Regex",
         typeParameters = emptyList(),
         isInstanceCreationAllowed = true,
         primaryConstructorParameters = listOf(CustomFunctionParameter("value", "String")),
         constructInstance = { interpreter, callArguments, callPosition ->
             RegexValue(Regex((callArguments[0] as StringValue).value), interpreter.symbolTable())
         },
         position = SourcePosition("Regex", 1, 1),
     )
}
----

NOTE: 工厂函数名称必须是 `${ActualTypeName}Value`。它适用于任何类型，无论原语或接口。此约定在代码生成插件中是硬编码的。

通过编写所有要委托的全局或扩展函数和扩展属性来创建一个 Kotlin 头文件，但不写主体。此文件应放在 `/your-library/src/kotlinheader/${LibraryName}.kt` 中。

[source, kotlin]
----
fun String.matches(regex: Regex): Boolean
fun String.replace(regex: Regex, replacement: String): String
fun String.replaceFirst(regex: Regex, replacement: String): String
fun String.toRegex(): Regex

val <T> List<T>.size: Int
    get()
val <T> List<T>.lastIndex: Int
    get()
----

编译时，将生成一个抽象类 `Abstract${name}LibModule`。检查生成的代码是否可编译且正确。可以通过编写单元测试来检查。

.生成代码的示例
[%collapsible]
====
./stdlib/build/generated/common/AbstractRegexLibModule.kt
[source, kotlin]
----
include::../../stdlib/build/generated/common/AbstractRegexLibModule.kt[]
----
====

NOTE: 代码生成插件有很多硬编码。您可能想要分支另一个并添加更多硬编码内容。

最后，创建一个类 `${name}LibModule` 扩展这个抽象类，必要时覆盖或添加任何内容，然后就完成了。

./stdlib/src/commonMain/kotlin/com/sunnychung/lib/multiplatform/kotlite/stdlib/RegexLibModule.kt
[source, kotlin]
----
include::../../stdlib/src/commonMain/kotlin/com/sunnychung/lib/multiplatform/kotlite/stdlib/RegexLibModule.kt[]
----

=== 空值

在正常情况下，Kotlite 的 `null` 值在传递给委托调用之前会映射为 `NullValue`。如果委托函数需要真实的 `null` 值才能正常工作，例如 `setOfNotNull()` 或 `filterNotNull`，则被视为空值感知。

在这种情况下，在 Kotlin 头文件中为这些函数添加 `nullaware` 修饰符，然后生成的代码会将 `NullValue` 映射为 `null`。例如：

./stdlib/src/kotlinheader/Collections.kt
[source, kotlin]
----
nullaware fun <T : Any> Iterable<T?>.filterNotNull(): List<T>
nullaware fun <T : Any> setOfNotNull(vararg elements: T?): Set<T>
----

== 委托给 Kotlin 值的 `equals()`、`hashCode()`、`toString()`

出于安全原因，它们默认不会被委托。需要显式的委托声明。

对于手动方法，下面是一个委托 `CustomClass.toString()` 的示例。

[source, kotlin]
----
val env = ExecutionEnvironment().apply {
    registerClass(CustomClass.clazz)
    registerFunction(CustomFunctionDefinition(
        position = SourcePosition.NONE,
        receiverType = "CustomClass",
        functionName = "toString",
        returnType = "String",
        parameterTypes = emptyList(),
        executable = { interpreter, receiver, args, typeArgs ->
            StringValue((receiver as DelegatedValue<*>).value.toString(), interpreter.symbolTable())
        }
    ))
}
----

对于委托方法，在 Kotlin 头文件中声明。下面是一个委托 `KInstant.toString()` 的示例。

./stdlib/src/kotlinheader/KDateTime.kt
[source, kotlin]
----
fun KInstant.toString(): String
----

== 分发

Kotlite 不提供分发或托管库的方法。将源代码放在 GitHub 上并创建一个 `awesome-kotlite` 仓库可能是一个选择。
