= 入门指南

== 包含依赖项

首先，包含依赖项。

Kotlite 解释器 image:https://img.shields.io/maven-central/v/io.github.sunny-chung/kotlite-interpreter[]

Kotlite 标准库 image:https://img.shields.io/maven-central/v/io.github.sunny-chung/kotlite-stdlib[]

对于单平台：

[source, kotlin]
----
dependencies {
    implementation("io.github.sunny-chung:kotlite-interpreter:<version>")
    implementation("io.github.sunny-chung:kotlite-stdlib:<version>")
    // ...
}
----

对于多平台：

[source, kotlin]
----
kotlin {
    sourceSets {
        val commonMain by getting {
            dependencies {
                api("io.github.sunny-chung:kotlite-interpreter:<version>")
                api("io.github.sunny-chung:kotlite-stdlib:<version>")
                // ...
            }
        }
        // ...
----

== 阶段

[mermaid]
----
flowchart LR
    subgraph K["KotliteInterpreter()"]
        ParseCode["解析代码"] --> Syntax["语法检查"] --> Analysis["语义分析"]
    end

    subgraph eval["Interpreter.eval()"]
        Execute["执行代码"]
    end

    Analysis --> Execute
----

开发者应该熟悉大部分阶段。

在语义分析阶段，它会做很多事情，比如检查类中的函数是否试图覆盖不存在的函数、返回错误数据类型的值、类型推断、代码优化等等。

任何阶段都可能抛出异常。

不同块中的阶段不需要在前一个阶段之后立即调用。

== 最小示例

了解了这些阶段后，我们可以开始编写代码了。

=== 打印 `Hello world!`

[source, kotlin]
----
val env = ExecutionEnvironment().apply {
    install(AllStdLibModules())
}
val interpreter = KotliteInterpreter(
    filename = "Hello",
    code = """
        println("Hello world!")
    """.trimIndent(),
    executionEnvironment = env,
)
interpreter.eval()
----

CAUTION: 解析和语义分析在 `KotliteInterpreter()` 函数中执行。可以将其想象为一个"编译过程"。如果有任何错误，在 `eval()` 调用之前，会从这个函数抛出异常。

NOTE: `filename` 参数仅用于错误消息和堆栈跟踪。

=== 获取执行结果的全局值
[source, kotlin]
----
val env = ExecutionEnvironment().apply {
    install(AllStdLibModules())
}
val interpreter = KotliteInterpreter(
    filename = "Calculate",
    code = """
        val a = (1..10).fold(0) { acc, it ->
            acc + it
        }
    """.trimIndent(),
    executionEnvironment = env,
)
interpreter.eval()
val symbolTable = interpreter.symbolTable()
val a = (symbolTable.findPropertyByDeclaredName("a") as IntValue).value // 55
----

=== 仅计算一个表达式

[source, kotlin]
----
val env = ExecutionEnvironment().apply {
    install(AllStdLibModules())
}
val result: IntValue = evalKotliteExpression(
    filename = "Calculate",
    code = "(1..10).fold(0) { acc, it -> acc + it }",
    executionEnvironment = env,
) as IntValue
val a: Int = result.value // 55
----

== 值和类型类

`evalKotliteExpression()` 或 `SymbolTable.findPropertyByDeclaredName()` 或 `Interpreter.eval()` 返回的所有值，或提供给自定义函数/属性的值参数，都是 `RuntimeValue` 的子类型。`RuntimeValue` 的可能子类型有：

* `IntValue`
* `LongValue`
* `DoubleValue`
* `CharValue`
* `StringValue`
* `BooleanValue`
* `ByteValue`
* `NullValue`
* `UnitValue`
* `LambdaValue`
* `ThrowableValue`
* `ClassInstance`

`RuntimeValue` 有一个成员函数 `type()`，它返回底层值的类型。返回类型是 `DataType` 的子类型。当有类型参数提供给自定义函数/属性时，也会提供 `DataType`。

供消费者使用的 `DataType` 的可能子类型有：

* `ObjectType`
* `FunctionType`
* `UnitType`
* `NothingType`
* `TypeParameterType`
* `StarType`
* `RepeatedType`

在大多数情况下，会返回 `ObjectType`。可以在 `ObjectType` 类中访问底层类定义、泛型类型参数和可空性。

`DataType` 有一个字符串成员属性 `descriptiveName`，它返回一个可读的类型名称，例如，`"MutableMap<MyPair<Int, Boolean>, List<String?>>?"`。

== 线程安全

解释器本身*不是*线程安全的。Kotlite 解释器执行的代码不能在多个线程上运行。

然而，Kotlite 解释器不保存全局状态。因此，可以运行不同的解释器实例并在多个线程中并发执行是可能的。

如果在提供的自定义函数中强制执行互斥锁，它也可能工作。

== 可重用性

大多数 Kotlite 类不能重用，包括 `ExecutionEnvironment`、AST 节点、解析器和解释器。它们包含状态。如果想要重复执行或使用相同的 `ExecutionEnvironment` 输入，必须重复调用。
