= 安全

== 标准库委托

标准库是通过委托给主机环境中的原始 Kotlin / 第三方 API 和类来实现的。例如，库函数 `fun String.toRegex(): Regex` 的实现会将 `StringValue` 转换为主机环境中的真实 `String`，然后调用 `toRegex()`，并以包装形式将 `Regex` 实例返回给嵌入式环境。这种委托方法可能会带来安全隐患。

虽然大多数 Kotlite 内置标准库执行起来应该是安全的，但委托给某些第三方库可能是不想要的。

== 过滤类、函数和属性

因此，Kotlite 提供了一种从嵌入式执行环境中移除它们的方法。

这可以通过向 `ExecutionEnvironment` 提供过滤函数来完成。

内置的东西，例如 `Int`，也可以被过滤掉，但这可能会在代码执行和导入库期间造成问题，并且没有安全收益。

下面是一个在不破坏环境的情况下完全移除类 `MutableList` 的示例。

[source, kotlin]
----
val env = ExecutionEnvironment(
    classRegistrationFilter = {
        it != "MutableList"
    },
    functionRegistrationFilter = {
        !(it.receiverType ?: "").contains("MutableList") &&
            !it.returnType.contains("MutableList")
    },
).apply {
    install(AllStdLibModules())
}

assertFailsWith<SemanticException> {
    KotliteInterpreter(
        filename = "<Test>",
        code = """
            val a = mutableListOf(1, 2, 3)
        """.trimIndent(),
        executionEnvironment = env
    )
}
----

NOTE: 开发者仍然可以创建一个具有相同名称的类，就像该类从未存在过一样。这不会造成危害，因为它不会与主机交互。

== 选择性地安装库

可以只将特定的库安装到 `ExecutionEnvironment` 中。

[source, kotlin]
----
val env = ExecutionEnvironment().apply {
    install(TextLibModule())
    install(CollectionsLibModule())
    install(ByteLibModule())
}
----

顺序很重要。如果一个库模块依赖另一个模块，被依赖的模块应该先安装。

== `equals()`、`hashCode()`、`toString()`、`compareTo()` 中的隐式代码执行

正如前面提到的，标准库只是对真实 API 和类的委托。

为了支持对自定义类的列表进行排序或使用自定义类作为 `Map` 的键的用例，最终用户可以在 Kotlite 中覆盖 `equals()`、`hashCode()`、`toString()`、`compareTo()` 函数。在主机环境中，调用这些函数将执行用户覆盖的代码，并可能抛出异常。这可能是不想要的代码执行和风险。

请记住，在您的应用程序中执行 `a == b` 或 `"Debug: $a"` 可能会执行用户代码。

== 资源使用

目前没有办法限制用户代码执行的内存使用或计算资源。用户代码可以通过无限循环耗尽所有可用内存或减慢操作系统。这一领域可能会在未来得到改善。
